In [ ]:
import numpy as np

In [ ]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
x.shape

(4, 2)

In [ ]:
y = np.array([0,0,0,1]).T
y.shape

(4,)

In [ ]:
x.shape,y.shape

((4, 2), (4,))

In [ ]:
def sigmoid(z):
    return (1/1+np.exp(-z))

In [ ]:
def derivative_sigmoid(z):
    return sigmoid(z)*(1-sigmoid(z))

In [ ]:
# without any hidden layer
weights = 2*np.random.random((2,1)) -1

In [ ]:
weights

array([[ 0.44065529],
       [-0.41436776]])

In [ ]:
bias = 2*np.random.random((1))-1

In [ ]:
bias

array([-0.01892003])

In [ ]:
#forward propagation
output0 = x
output = sigmoid(np.dot(output0,weights)+bias)

In [ ]:
output

array([[2.01910015],
       [2.54232002],
       [1.65590766],
       [1.99265958]])

In [ ]:
wh = 2*np.random.random((2,2)) -1
bh = 2*np.random.random((1,2)) -1
wh,bh

(array([[ 0.03727525,  0.6700527 ],
        [-0.91681337, -0.67728098]]), array([[-0.83862221,  0.45519617]]))

In [ ]:
w0 = 2*np.random.random((2,1))-1
b0 = 2*np.random.random((1,1))-1
w0,b0

(array([[0.88655262],
        [0.21331546]]), array([[0.18386087]]))

In [ ]:
output0 = x
outputHidden = sigmoid(np.dot(output0,wh)+bh)
outputHidden.shape
outputHidden

array([[3.31317771, 1.63432352],
       [6.78596747, 2.24867726],
       [3.22854066, 1.32457168],
       [6.57426423, 1.63892519]])

In [ ]:
finalOutput = sigmoid(np.dot(outputHidden,w0)+b0)

In [ ]:
finalOutput

array([[1.03112345],
       [1.00125621],
       [1.03584025],
       [1.00172608]])

# basic neural network i.e., no hidden layer

In [ ]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
X.shape

(4, 2)

In [ ]:
Y = np.array([[0,0,0,1]]).T

In [ ]:
def sig(z):
    return 1/(1+np.exp(-z))

In [ ]:
def derivative_sig(z):
    return sig(z)*(1-sig(z))

In [ ]:
new_weights = 2*np.random.random((2,1)) -1
new_bias = 2*np.random.random((1))-1
lr = 0.1

In [ ]:
for i in range(100000):
    new_output0 = X
    new_output = sig(np.dot(new_output0, new_weights) + new_bias)

    first_term = new_output - Y
    input_for_first_layer = np.dot(new_output0, new_weights) + new_bias
    second_term = derivative_sig(input_for_first_layer)
    first_two = first_term * second_term
    first_two.shape

    changes = np.array([[0.0],[0.0]])  # considering this shape becoze the shape of new_weights is (2 x 1)
    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two[j][0] * new_output0[j][i]
    changes
    new_weights = new_weights - lr*changes

    bias_change = 0.0
    for j in range(4):
            bias_change += first_two[j][0] * 1
    new_bias = new_bias - lr*bias_change


In [ ]:
new_output = sig(np.dot(X, new_weights) + new_bias)

In [ ]:
new_weights,new_bias

(array([[8.01881584],
        [8.01881584]]), array([-12.11468979]))

In [ ]:
new_output

array([[5.47841209e-06],
       [1.63688001e-02],
       [1.63688001e-02],
       [9.80600958e-01]])

In [ ]:
# this is the same procedure but instead of looping just use vector multiplication
for i in range(100000):
    new_output0 = X
    new_output = sig(np.dot(new_output0, new_weights) + new_bias)

    first_term = new_output - Y
    input_for_first_layer = np.dot(new_output0, new_weights) + new_bias
    second_term = derivative_sig(input_for_first_layer)
    first_two = first_term * second_term
    first_two.shape

    changes = np.array([[0.0],[0.0]])  # considering this shape becoze the shape of new_weights is (2 x 1)
    changes = np.dot(new_output0.T, first_two)
    changes
    new_weights = new_weights - lr*changes

    bias_change = np.sum(first_two)
    new_bias = new_bias - lr*bias_change
new_output = sig(np.dot(X, new_weights) + new_bias)
changes,bias_change,new_output

(array([[-5.19157978e-05],
        [-5.19157978e-05]]), 7.78311211770011e-05, array([[1.84773363e-06],
        [1.14564353e-02],
        [1.14564353e-02],
        [9.86429408e-01]]))

# forward propagation and backward propagation code for neural network which has hidden layer

In [ ]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])

In [ ]:
Y = np.array([[0,1,1,0]]).T

In [ ]:
def hsig(z):
    return 1/(1+np.exp(-z))

In [ ]:
def hderivative_sig(z):
    return hsig(z)*(1-hsig(z))

In [ ]:
weight_hidden = 2*np.random.random((2,2))-1
bias_hidden = 2*np.random.random((1,2))-1
weight_output = 2*np.random.random((2,1))-1
bias_output = 2*np.random.random((1,1))-1
learning_rate = 0.1

In [ ]:
#forward propagation
for i in range(100000):
    h_output0 = X
    input_hidden = np.dot(h_output0,weight_hidden)+bias_hidden
    h_output_hidden = hsig(input_hidden)
    inputForOutputLayer = np.dot(h_output_hidden,weight_output)+bias_output
    h_output = hsig(inputForOutputLayer)

    #this is for the outer most layer where y_pred is done
    first_term_for_output_layer = h_output - Y
    second_term_for_output_layer = hderivative_sig(inputForOutputLayer)
    first_two_output_layer = first_term_for_output_layer * second_term_for_output_layer

    #this is for the hidden layer i.e., we r using the backpropagation
    first_term_hidden_layer = np.dot(first_two_output_layer, weight_output.T)
    second_term_hidden_layer = hderivative_sig(input_hidden)
    first_two_hidden_layer = first_term_hidden_layer * second_term_hidden_layer

    #   for i in range(100000):
    #     new_output0 = X
    #       new_output = sig(np.dot(new_output0, new_weights) + new_bias)
    #
    #       first_term = new_output - Y
    #        input_for_first_layer = np.dot(new_output0, new_weights) + new_bias
    #        second_term = derivative_sig(input_for_first_layer)
    #        first_two = first_term * second_ter#m
    #        first_two.shape

    #        changes = np.array([[0.0],[0.0]])  # considering this shape becoze the shape of new_weights is (2 x 1)
    #        changes = np.dot(new_output0.T, first_two)
    #        changes
    #        new_weights = new_weights - lr*changes

    #        bias_change = np.sum(first_two)
    #        new_bias = new_bias - lr*bias_change

    # here on the calculation part for finding the changes of the current layer we require first_two_terms of current_layer with the
    # multiplication of the previous layer in Transpose to back propagate the error
    changes_output = np.dot(h_output_hidden.T, first_two_output_layer)
    changes_output_bias = np.sum(first_two_output_layer, axis = 0,keepdims = True)

    changes_hidden = np.dot(h_output0.T, first_two_hidden_layer)
    changes_hidden_bias = np.sum(first_two_hidden_layer, axis = 0,keepdims = True)

    weight_output = weight_output - learning_rate * changes_output
    bias_output = bias_output - learning_rate * changes_output_bias

    weight_hidden = weight_hidden - learning_rate * changes_hidden
    bias_hidden = bias_hidden - learning_rate * changes_hidden_bias
    
h_output0 = X
input_hidden = np.dot(h_output0,weight_hidden)+bias_hidden
h_output_hidden = hsig(input_hidden)
inputForOutputLayer = np.dot(h_output_hidden,weight_output)+bias_output
h_output = hsig(inputForOutputLayer)

h_output,weight_hidden,bias_hidden,weight_output,bias_output

(array([[0.01086209],
        [0.98765156],
        [0.9876511 ],
        [0.01160571]]), array([[ 5.08407881, -6.41605366],
        [ 5.08422768, -6.4166316 ]]), array([[-7.89383583,  2.55738282]]), array([[-10.63854654],
        [-10.46234282]]), array([[5.2021773]]))